### ISSUE TITLE
v2.1.4 not working with Arduino SDK 2.4

### ISSUE THREAD

**Issue by sidoh** [Links2004/arduinoWebSockets#447]
Build fails with this:

```
.pio/libdeps/d1_mini/WebSockets_ID549/src/WebSocketsClient.cpp: In member function 'void WebSocketsClient::connectedCb()':
.pio/libdeps/d1_mini/WebSockets_ID549/src/WebSocketsClient.cpp:749:22: error: 'class axTLS::WiFiClientSecure' has no member named 'setInsecure'
         _client.ssl->setInsecure();
                      ^
Compiling .pio/build/d1_mini/lib154/ESP Async WebServer_ID306/WebRequest.cpp.o
.pio/libdeps/d1_mini/WebSockets_ID549/src/WebSocketsServer.cpp: In member function 'bool WebSocketsServer::newClient(WiFiClient*)':
.pio/libdeps/d1_mini/WebSockets_ID549/src/WebSocketsServer.cpp:465:23: warning: variable 'ip' set but not used [-Wunused-but-set-variable]
             IPAddress ip = client->tcp->remoteIP();
                       ^
.pio/libdeps/d1_mini/WebSockets_ID549/src/WebSocketsServer.cpp: In member function 'void WebSocketsServer::handleNewClients()':
.pio/libdeps/d1_mini/WebSockets_ID549/src/WebSocketsServer.cpp:638:23: warning: variable 'ip' set but not used [-Wunused-but-set-variable]
             IPAddress ip = tcpClient->remoteIP();
                       ^
```

Looks related to this commit: https://github.com/Links2004/arduinoWebSockets/commit/df3ef524b6b481939c184f2a044dcbaf00b83a6f.

Guessing this is because `USING_AXTLS` was not introduced until 2.5 since it was the default.  Maybe need a check for SDK version here as well?

Workaround might be to have upstream projects on 2.4 define `USING_AXTLS`, but feels less than ideal.

**Comment by sidoh** [comment]
(also -- and more importantly -- thank you for your hard work on this library!  does exactly what i need)

**Comment by Links2004** [comment]
Hi,

can you check with:

```cpp
    } else if(_client.isSSL && !_CA_cert) {
#if defined(wificlientbearssl_h) && !defined(USING_AXTLS) && !defined(wificlientsecure_h)
        _client.ssl->setInsecure();
#endif
    }
```
Thanks

**Comment by sidoh** [comment]
yep, that does the trick.  thank you!

**Comment by sidoh** [comment]
Thanks for the quick response!
