### ISSUE TITLE
Problem with updated version 2.0.2

### ISSUE THREAD

**Issue by TheAustrian** [Links2004/arduinoWebSockets#68]
Hello, my sketch won't compile with the 2.0.2 version - I get the following error messages (I did not copy the complete list since it seemed basically the same every time):
``` c++
    In file included from /Users/***/Documents/Arduino/ESP-Fado-Lamp/ESP-Fado-Lamp.ino:37:0:
sketch/LEDWebsockets.h: In function 'void webSocketEvent(uint8_t, WStype_t, uint8_t*, size_t)':
LEDWebsockets.h:21: error: no matching function for call to 'WebSocketsServer::sendTXT(uint8_t&, String)'
         webSocket.sendTXT(num, ESP.getResetInfo());
                                                  ^
sketch/LEDWebsockets.h:21:50: note: candidates are:
In file included from /Users/***/Documents/Arduino/ESP-Fado-Lamp/ESP-Fado-Lamp.ino:7:0:
/Users/***/Documents/Arduino/libraries/WebSockets/src/WebSocketsServer.h:60:14: note: bool WebSocketsServer::sendTXT(uint8_t, uint8_t*, size_t, bool)
         bool sendTXT(uint8_t num, uint8_t * payload, size_t length = 0, bool headerToPayload = false);

              ^
/Users/***/Documents/Arduino/libraries/WebSockets/src/WebSocketsServer.h:60:14: note:   no known conversion for argument 2 from 'String' to 'uint8_t* {aka unsigned char*}'
/Users/***/Documents/Arduino/libraries/WebSockets/src/WebSocketsServer.h:61:14: note: bool WebSocketsServer::sendTXT(uint8_t, const uint8_t*, size_t)
         bool sendTXT(uint8_t num, const uint8_t * payload, size_t length = 0);

              ^
/Users/***/Documents/Arduino/libraries/WebSockets/src/WebSocketsServer.h:61:14: note:   no known conversion for argument 2 from 'String' to 'const uint8_t* {aka const unsigned char*}'
/Users/***/Documents/Arduino/libraries/WebSockets/src/WebSocketsServer.h:62:14: note: bool WebSocketsServer::sendTXT(uint8_t, char*, size_t, bool)
         bool sendTXT(uint8_t num, char * payload, size_t length = 0, bool headerToPayload = false);

              ^
/Users/***/Documents/Arduino/libraries/WebSockets/src/WebSocketsServer.h:62:14: note:   no known conversion for argument 2 from 'String' to 'char*'
/Users/***/Documents/Arduino/libraries/WebSockets/src/WebSocketsServer.h:63:14: note: bool WebSocketsServer::sendTXT(uint8_t, const char*, size_t)
         bool sendTXT(uint8_t num, const char * payload, size_t length = 0);

              ^
/Users/***/Documents/Arduino/libraries/WebSockets/src/WebSocketsServer.h:63:14: note:   no known conversion for argument 2 from 'String' to 'const char*'
/Users/***/Documents/Arduino/libraries/WebSockets/src/WebSocketsServer.h:64:14: note: bool WebSocketsServer::sendTXT(uint8_t, String&)
         bool sendTXT(uint8_t num, String & payload);
```

The 2.0.0 version works normally. Anything I can do except reverting to the old version?

**Comment by Links2004** [comment]
try this:
```cpp
String info = ESP.getResetInfo();
webSocket.sendTXT(num, info);
```

**Comment by TheAustrian** [comment]
Thanks a lot, that worked! It did work the other way with the older version of the library so I would never have thought that that was it...
